
import __ASTRO_IMAGE_IMPORT_1GKPky from "./sara-cervera-xoclqoltbjs-unsplash.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fannouncing-pecans-an-update-server-for-squirrel%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZTxLT4 from "./drupalcon2008-feathered.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fa-drupal-multimedia-panel%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2qwFq8 from "./shannon_tattoo_mod2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Falways-within-my-circle-of-friends%2Findex.md";
import __ASTRO_IMAGE_IMPORT_fVzTK from "./shannon_tattoo_mod1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Falways-within-my-circle-of-friends%2Findex.md";
import __ASTRO_IMAGE_IMPORT_dtM3A from "./shannon_tattoo_mod8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Falways-within-my-circle-of-friends%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2i5ViS from "./Windows-8-logo-300x300.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdiving-into-windows-8-its-easy-to-get-your-desktop-back%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1CCWTa from "./d7-contributor-cloud-small.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffinally-personal-blog-on-d7%2Findex.md";
import __ASTRO_IMAGE_IMPORT_L5xrP from "./mt-gs.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Finstalling-bzr-on-media-templegs%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZyEigx from "./entertainment.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmy-home-entertainment-system%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1IRxui from "./posterboymaterial1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpunk-for-the-jaded-poster-boy-material%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z24bvMy from "./posterboymaterial2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpunk-for-the-jaded-poster-boy-material%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1x7dJf from "./header-logo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-news-is-nowpublic-im-working-for-nowpubliccom%2Findex.md";
import __ASTRO_IMAGE_IMPORT_aR4Xy from "./internet-archive.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frecovering-lost-content%2Findex.md";
import __ASTRO_IMAGE_IMPORT_17RLX6 from "./devshop-logo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-20-project-management-done-right%2Findex.md";
export default new Map([["./sara-cervera-xoclqoltbjs-unsplash.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fannouncing-pecans-an-update-server-for-squirrel%2Findex.md", __ASTRO_IMAGE_IMPORT_1GKPky], ["./drupalcon2008-feathered.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fa-drupal-multimedia-panel%2Findex.md", __ASTRO_IMAGE_IMPORT_ZTxLT4], ["./shannon_tattoo_mod2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Falways-within-my-circle-of-friends%2Findex.md", __ASTRO_IMAGE_IMPORT_2qwFq8], ["./shannon_tattoo_mod1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Falways-within-my-circle-of-friends%2Findex.md", __ASTRO_IMAGE_IMPORT_fVzTK], ["./shannon_tattoo_mod8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Falways-within-my-circle-of-friends%2Findex.md", __ASTRO_IMAGE_IMPORT_dtM3A], ["./Windows-8-logo-300x300.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdiving-into-windows-8-its-easy-to-get-your-desktop-back%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2i5ViS], ["./d7-contributor-cloud-small.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffinally-personal-blog-on-d7%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1CCWTa], ["./mt-gs.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Finstalling-bzr-on-media-templegs%2Findex.md", __ASTRO_IMAGE_IMPORT_L5xrP], ["./entertainment.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmy-home-entertainment-system%2Findex.md", __ASTRO_IMAGE_IMPORT_ZyEigx], ["./posterboymaterial1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpunk-for-the-jaded-poster-boy-material%2Findex.md", __ASTRO_IMAGE_IMPORT_1IRxui], ["./posterboymaterial2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpunk-for-the-jaded-poster-boy-material%2Findex.md", __ASTRO_IMAGE_IMPORT_Z24bvMy], ["./header-logo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-news-is-nowpublic-im-working-for-nowpubliccom%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1x7dJf], ["./internet-archive.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frecovering-lost-content%2Findex.md", __ASTRO_IMAGE_IMPORT_aR4Xy], ["./devshop-logo.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fweb-20-project-management-done-right%2Findex.md", __ASTRO_IMAGE_IMPORT_17RLX6]]);
		