excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://dopry.github.io
title: Darrel O'Pry
tagline: living one bug at a time...
description: These are the personal musings and rants of Darrel O'Pry. Darrel is a career technologist and entrepreneur. He currently runs <a href="https://spry-group.com">The Spry Group</a>, a full service digital product agency.
paginate: 5